name: Verify PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip ci' ) }}
    uses: ./.github/workflows/verify-workflow.yaml
    secrets:
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      AWS_CLUSTER_USERNAME: ${{ secrets.AWS_CLUSTER_USERNAME }}
      AWS_CLUSTER_PASSWORD: ${{ secrets.AWS_CLUSTER_PASSWORD }}
      AZURE_CLUSTER_USERNAME: ${{ secrets.AZURE_CLUSTER_USERNAME }}
      AZURE_CLUSTER_PASSWORD: ${{ secrets.AZURE_CLUSTER_PASSWORD }}
      GIT_ORG: ${{ secrets.GIT_ORG }}
      GIT_ADMIN_USERNAME: ${{ secrets.GIT_ADMIN_USERNAME }}
      GIT_ADMIN_TOKEN: ${{ secrets.GIT_ADMIN_TOKEN }}

  verifyMetadata:
    uses: cloud-native-toolkit/action-workflows/.github/workflows/verify-module-metadata.yaml@v1

  verifyAll:
    needs: ["verify","verifyMetadata"]
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Success"
